Page Layout
Abhiram716/personal-portfolio pull request #18
Opened 2023-09-03 07:16 UTC by Abhiram716

2023-09-03 16:55 UTC, Abhiram716 commented
@aadilmughal786,
I merged PR(#19) before this PR(#18), and then I rebased the local feature/page-layout branch after pulling the main branch in local. Because the remote branch is one commit behind the local branch after rebasing, I had to push the changes, which resulted in rebased files appearing in the files changes area. Is this the right way to rebase? or what I am doing is wrong.
This is my git config file
user.name=Abhiram Kantipudi
user.email=a4abhiram125@gmail.com
init.defaultbranch=main
pull.rebase=true
fetch.prune=true
diff.colormoved=zebra

2023-09-03 17:14 UTC, aadilmughal786 requested changes

2023-09-03 17:14 UTC, aadilmughal786 commented on src/components/Footer/index.jsx
> +            {`${new Date().getFullYear()} `}
Nice

2023-09-03 17:14 UTC, aadilmughal786 commented on src/components/Header/index.jsx
File naming is confusing because this is a component file, but the name is index.jsx
other component files names are starting from capital letter

2023-09-03 17:14 UTC, aadilmughal786 commented on src/components/Layout/Layout.jsx
> +      <>{children}</>
Why need extra fragment here?

2023-09-03 17:20 UTC, aadilmughal786 commented
> @aadilmughal786, I merged PR(#19) before this PR(#18), and then I rebased the local feature/page-layoutPR(#18) branch after pulling the main branch in local. Because the remote branch is one commit behind the local branch after rebasing, I had to push the changes, which resulted in rebased files appearing in the files changes area. Is this the right way to rebase? or what I am doing is wrong. This is my git config file user.name=Abhiram Kantipudi user.email=[a4abhiram125@gmail.com](mailto:a4abhiram125@gmail.com) init.defaultbranch=main pull.rebase=true fetch.prune=true diff.colormoved=zebra

LGTM, you can also watch this https://youtu.be/RxHJdapz2p0?si=VGLdbnaBH2ZQO8XM

2023-09-04 02:03 UTC, Abhiram716 commented on src/components/Layout/Layout.jsx
> +      <>{children}</>
Nope

2023-09-04 02:14 UTC, Abhiram716 commented on src/components/Header/index.jsx
My justification is an `index.jsx` file of a component is a parent file, and other files in the same component are children, and naming the file `header.jsx` kinda looks repetitive. Isn't it obvious what people are searching for when they see the folder name Header?
What are your opinions about it?

2023-09-04 02:55 UTC, Abhiram716 commented
@aadilmughal786,

I need a feature suggestion, I am trying to implement a smooth scroll feature when a user clicks on a link do you know any native API or libraries for that?

2023-09-06 16:21 UTC, aadilmughal786 commented
> @aadilmughal786,
> 
> I need a feature suggestion, I am trying to implement a smooth scroll feature when a user clicks on a link do you know any native API or libraries for that?

this will help 

```css
html {
    scroll-behavior: smooth;
}
```

2023-09-06 16:22 UTC, aadilmughal786 approved these changes
LGTM

2023-09-06 16:26 UTC, aadilmughal786 commented on src/components/Header/index.jsx
Yes, this will also work. It is very opinionated thing

2023-09-06 17:17 UTC, merged